import React from 'react'
import { BriefcaseBusiness, Building2, CheckCircle2, Globe2, GraduationCap, Mail, Menu, Phone, ShieldCheck, Truck, UserCheck, Users, X, ArrowRight, MapPin } from 'lucide-react'

const talent = ['South African delivery riders','Professional drivers','Code 10 / Code 14 drivers','International driving opportunities','Sales Development Representatives (SDRs)','Virtual & administrative assistants','Retail & general workforce','Selected international opportunities']
const employers = ['Local recruitment','International recruitment','Driver recruitment','Workforce training','Candidate screening & verification','Bulk recruitment','Talent pipeline solutions']
const steps:any[] = [[Users,'Recruit','We source candidates through targeted talent networks and recruitment campaigns.'],[GraduationCap,'Train','We support workforce readiness and role-specific preparation where appropriate.'],[UserCheck,'Verify','We screen candidates and verify relevant information, licences and experience.'],[BriefcaseBusiness,'Place','We connect suitable, eligible candidates with genuine employer opportunities.']]
const wa='https://wa.me/27762139272'

export default function App(){
 const [open,setOpen]=React.useState(false)
 const [page,setPage]=React.useState(location.hash.replace('#/','')||'home')
 React.useEffect(()=>{const f=()=>{setPage(location.hash.replace('#/','')||'home');scrollTo(0,0)};addEventListener('hashchange',f);return()=>removeEventListener('hashchange',f)},[])
 const go=(p:string)=>`#/${p}`
 const nav=(p:string,label:string)=><a href={go(p)} onClick={()=>setOpen(false)}>{label}</a>
 const Header=()=> <><header className="nav"><div className="wrap navin"><a href={go('home')} className="brand"><img src="/talent-bridge-logo.jpeg"/><span><b>Talent Bridge Global</b><small>Connecting Talent. Creating Opportunity.</small></span></a><nav className="desktop">{nav('home','Home')}{nav('talent','For Talent')}{nav('employers','For Employers')}{nav('services','Services')}{nav('about','About')}{nav('contact','Contact')}</nav><a className="call desktop" href="tel:+27762139272"><Phone size={16}/> Call Us</a><button aria-label="Menu" className="mobile menu" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></div>{open&&<div className="mobile mobnav">{nav('home','Home')}{nav('talent','For Talent')}{nav('employers','For Employers')}{nav('services','Services')}{nav('about','About')}{nav('contact','Contact')}</div>}</header></>
 const Footer=()=> <footer><div className="wrap foot"><div className="brand"><img src="/talent-bridge-logo.jpeg"/><span><b>Talent Bridge Global</b><small>Connecting Talent. Creating Opportunity.</small></span></div><p>Recruit. Train. Verify. Place.</p><small>© {new Date().getFullYear()} Talent Bridge Global.</small></div></footer>
 const Contact=()=> <section className="contact"><div className="wrap split contactgrid"><div><span className="tag gold">Contact Us</span><h2>Ready to connect talent with opportunity?</h2><p>Whether you are looking for work or looking to hire, speak to Talent Bridge Global.</p><div className="contactlinks"><a href="tel:+27762139272"><Phone/> +27 76 213 9272</a><a href="mailto:info@talentbridgeglobal.co.za"><Mail/> info@talentbridgeglobal.co.za</a><span><MapPin/> South Africa</span></div></div><div className="contactbox"><h3>Quick Enquiry</h3><p>Choose the conversation that best matches what you need.</p><a className="primary full" href={`${wa}?text=Hello%20Talent%20Bridge%20Global%2C%20I%20am%20looking%20for%20work.`} target="_blank">I’m Looking for Work</a><a className="bluebtn full" href={`${wa}?text=Hello%20Talent%20Bridge%20Global%2C%20I%20would%20like%20to%20hire%20talent.`} target="_blank">I’m Hiring Talent</a><a className="mailbtn full" href="mailto:info@talentbridgeglobal.co.za?subject=Talent%20Bridge%20Global%20Enquiry">Send an Email</a></div></div></section>
 const Home=()=> <><section className="hero"><div className="heroPhoto"/><div className="overlay"/><div className="wrap heroContent"><span className="eyebrow">Talent Bridge Global • South Africa</span><h1>Connecting Talent.<br/><em>Creating Opportunity.</em></h1><p>We connect people with genuine employment opportunities while helping businesses access the talent they need to grow — across South Africa and selected international markets.</p><div className="actions"><a href={go('talent')} className="primary"><Users size={18}/> I’m Looking for Work <ArrowRight/></a><a href={go('employers')} className="secondary"><BriefcaseBusiness size={18}/> I’m Hiring Talent <ArrowRight/></a></div><div className="heroProof"><b>200+ drivers placed</b><span>Real placements. Growing African talent network.</span></div></div></section><section className="stats"><div className="wrap grid4"><div><Users/><b>200+</b><span>Drivers placed</span></div><div><ShieldCheck/><b>Verified</b><span>Candidate screening</span></div><div><Globe2/><b>Local + Global</b><span>Opportunities</span></div><div><Building2/><b>Employer-led</b><span>Recruitment solutions</span></div></div></section><section className="section"><div className="wrap split"><div className="photoCard talentPhoto"><div><span className="tag gold">For Talent</span><h2>Find real opportunities. Build your future.</h2><a href={go('talent')} className="primary">Explore Opportunities <ArrowRight/></a></div></div><div className="photoCard employerPhoto"><div><span className="tag gold">For Employers</span><h2>Access reliable talent. Grow your business.</h2><a href={go('employers')} className="primary">Hire Talent <ArrowRight/></a></div></div></div></section><Approach/><Contact/></>
 const Approach=()=> <section className="section light"><div className="wrap"><div className="center"><span className="tag">Our Approach</span><h2>Recruit. Train. Verify. Place.</h2></div><div className="cards4">{steps.map(([Icon,title,text],i)=><article key={title}><span className="num">0{i+1}</span><Icon/><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
 const Talent=()=> <><PageHero title="For Talent" text="Find genuine opportunities. Build your profile. Take the next step in your career." cls="talentPage"/><section className="section"><div className="wrap split"><div><span className="tag">Opportunities</span><h2>Built around the changing world of work.</h2><p>We build talent pipelines across driving, delivery, sales, administration, retail, logistics and selected international opportunities.</p><div className="list blue one">{talent.map(x=><div key={x}><CheckCircle2 size={18}/>{x}</div>)}</div></div><div className="applybox"><h2>Join our talent network</h2><p>Tell us about your skills, experience, licence category and the type of work you are seeking.</p><a className="primary full" target="_blank" href={`${wa}?text=Hello%20Talent%20Bridge%20Global.%20I%20would%20like%20to%20join%20your%20talent%20network.%20My%20name%20is%3A%20`}>Apply via WhatsApp</a><a className="mailbtn full" href="mailto:info@talentbridgeglobal.co.za?subject=Candidate%20Application">Apply via Email</a></div></div></section><Approach/><Contact/></>
 const Employers=()=> <><PageHero title="For Employers" text="Recruitment solutions designed around your workforce requirements." cls="employerPage"/><section className="section"><div className="wrap split"><div><span className="tag">Employer Solutions</span><h2>Access the talent you need to grow.</h2><p>We support local and international employers with sourcing, screening, workforce readiness and recruitment partnerships.</p><div className="list blue one">{employers.map(x=><div key={x}><CheckCircle2 size={18}/>{x}</div>)}</div></div><div className="applybox"><h2>Tell us who you need</h2><p>Send your role, location, headcount and key requirements and our team can discuss the right recruitment approach.</p><a className="primary full" target="_blank" href={`${wa}?text=Hello%20Talent%20Bridge%20Global.%20I%20am%20an%20employer%20and%20need%20recruitment%20support.`}>Request Talent via WhatsApp</a><a className="mailbtn full" href="mailto:info@talentbridgeglobal.co.za?subject=Employer%20Recruitment%20Request">Email Recruitment Request</a></div></div></section><Contact/></>
 const Services=()=> <><PageHero title="Recruitment Services" text="From sourcing to placement, we help build stronger workforce pipelines." cls="servicesPage"/><section className="section"><div className="wrap cards4">{employers.map((x,i)=><article key={x}><BriefcaseBusiness/><h3>{x}</h3><p>{['Targeted sourcing for South African businesses.','Selected cross-border talent sourcing aligned to eligibility and employer requirements.','Delivery, professional, Code 10 and Code 14 driver talent pipelines.','Workforce-readiness support where appropriate.','Relevant candidate information, experience and licence screening.','Scalable sourcing for higher-volume workforce requirements.','Ongoing pipelines that help employers prepare for future hiring needs.'][i]}</p><a href={go('contact')} className="textlink">Enquire <ArrowRight size={16}/></a></article>)}</div></section><Contact/></>
 const About=()=> <><PageHero title="About Talent Bridge Global" text="Connecting Talent. Creating Opportunity." cls="aboutPage"/><section className="section"><div className="wrap narrow center"><span className="tag">Who We Are</span><h2>Recruitment is about more than filling vacancies.</h2><p>Talent Bridge Global exists to connect people with genuine employment opportunities while helping businesses access the talent they need to grow.</p><p>Our approach brings together talent sourcing, screening, workforce readiness and recruitment partnerships across South Africa and selected international markets.</p><h2>Our Commitment</h2><p>We believe in transparency. We do not promise employment where no vacancy exists and we do not guarantee international placement. Opportunities depend on employer requirements, candidate eligibility and available vacancies.</p><h2>Our Vision</h2><p>To become a trusted workforce partner connecting African talent with opportunities locally and globally.</p></div></section><section className="milestone"><div className="wrap center"><Truck size={52}/><strong>200+</strong><h2>Drivers placed</h2><p>A genuine placement milestone — not an inflated claim.</p></div></section><Contact/></>
 function PageHero({title,text,cls}:{title:string,text:string,cls:string}){return <section className={`pageHero ${cls}`}><div className="overlay"/><div className="wrap pageHeroIn"><span className="eyebrow">Talent Bridge Global</span><h1>{title}</h1><p>{text}</p></div></section>}
 let content:any=page==='talent'?<Talent/>:page==='employers'?<Employers/>:page==='services'?<Services/>:page==='about'?<About/>:page==='contact'?<><PageHero title="Contact Talent Bridge Global" text="Candidates and employers — connect with our team." cls="contactPage"/><Contact/></>:<Home/>
 return <div><Header/>{content}<Footer/></div>
}
